//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int studentId { get; set; }
        public string sname { get; set; }
        public string degree { get; set; }
        public string city { get; set; }
        public string gender { get; set; }
    }
}
