//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBook
    {
        public int bookid { get; set; }
        public string book_name { get; set; }
        public string author { get; set; }
        public string publication { get; set; }
        public string subject { get; set; }
    }
}
